name: loc-pred
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.12
  - cudatoolkit=11.3
  - pytorch=1.12.1
  - trackintel=1.2.4
  - gensim
  - easydict
  - yaml
  - pyyaml
  - transformers=4.16.2

    
